# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import image_pb2 as image__pb2


class GreeterStub(object):
  """The greeting service definition.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.printimage = channel.unary_unary(
        '/image.Greeter/printimage',
        request_serializer=image__pb2.imageRequest.SerializeToString,
        response_deserializer=image__pb2.imageReply.FromString,
        )


class GreeterServicer(object):
  """The greeting service definition.
  """

  def printimage(self, request, context):
    """Sends a picture
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_GreeterServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'printimage': grpc.unary_unary_rpc_method_handler(
          servicer.printimage,
          request_deserializer=image__pb2.imageRequest.FromString,
          response_serializer=image__pb2.imageReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'image.Greeter', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
